hubot_env:
  HUBOT_LOGLEVEL: "info"
  HUBOT_SLACK_TOKEN: ""
  TZ: "America/New_York"
  EXPRESS_PORT: 8080
  WORDNIK_API_KEY: ""
  HUBOT_GOOGLE_API_KEY: ""
  HUBOT_YOUTUBE_API_KEY: HUBOT_GOOGLE_API_KEY
  HUBOT_YOUTUBE_DETERMINISTIC_RESULTS: "true"
  STEAM_API_KEY: ""
  WOTD_PROVIDER: "wordnik"
  LIVESTREAM_BROADCAST_ROOM: '"#feed-games"'
  HUBOT_AUTH_ROLES: '"admin=derimagia"'